#!/usr/bin/env python3
"""Automated report generation — daily/weekly/monthly quant strategy reports.

Integrates all quant_framework modules to produce comprehensive markdown reports.
Uses existing module report functions where available."""

from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd


@dataclass
class ReportConfig:
    output_dir: str = "company/reports"
    include_charts: bool = False  # PNG chart embedding
    include_factor_analysis: bool = True
    include_risk_metrics: bool = True
    include_performance_attribution: bool = True
    include_stress_test: bool = True
    include_execution_summary: bool = True
    top_n_factors: int = 10
    benchmark_name: str = "S&P 500"
    strategy_name: str = "Multi-Factor Alpha"


# ── Daily Briefing ─────────────────────────────────────────


def generate_daily_briefing(
    signals: pd.DataFrame | None = None,
    positions: pd.DataFrame | None = None,
    pnl: pd.Series | None = None,
    factor_ic: pd.DataFrame | None = None,
    market_data: pd.DataFrame | None = None,
    config: ReportConfig | None = None,
) -> str:
    """Generate daily briefing report.

    Parameters
    ----------
    signals: latest signals DataFrame [ticker, signal, score]
    positions: current positions [ticker, shares, weight, value]
    pnl: daily PnL Series
    factor_ic: latest factor IC values
    market_data: current market snapshot
    config: ReportConfig
    """
    if config is None:
        config = ReportConfig()

    today = datetime.now()
    lines = [
        f"# {config.strategy_name} — Daily Briefing",
        f"**{today.strftime('%Y-%m-%d (%A)')}**",
        "",
        "---",
        "",
    ]

    # Market snapshot
    if market_data is not None and not market_data.empty:
        lines += ["## Market Snapshot", ""]
        ret_col = None
        for c in ["return", "daily_return", "ret_1d"]:
            if c in market_data.columns:
                ret_col = c
                break

        if ret_col:
            lines.append(f"**Market Return**: {market_data[ret_col].mean():.2%}  ")
        if "volatility" in market_data.columns:
            lines.append(f"**Realized Vol**: {market_data['volatility'].mean():.2%}  ")
        if "volume" in market_data.columns:
            lines.append(f"**Volume**: {market_data['volume'].mean():,.0f}  ")
        lines.append("")

    # PnL summary
    if pnl is not None and len(pnl) > 0:
        total_pnl = float(pnl.sum())
        lines += [
            "## P&L Summary",
            "",
            f"**Daily P&L**: ${total_pnl:,.0f}  ",
            f"**Win Rate (5D)**: {(pnl.tail(5) > 0).mean():.0%}  ",
            "",
        ]

    # Signal overview
    if signals is not None and not signals.empty:
        n_long = int((signals.get("signal", 0) == 1).sum())
        n_short = int((signals.get("signal", 0) == -1).sum())
        n_neutral = len(signals) - n_long - n_short
        lines += [
            "## Signal Overview",
            "",
            f"**Long**: {n_long} | **Short**: {n_short} | **Neutral**: {n_neutral}  ",
            "",
        ]

        if "score" in signals.columns or "combined_score" in signals.columns:
            score_col = (
                "combined_score" if "combined_score" in signals.columns else "score"
            )
            top_5 = signals.nlargest(5, score_col)
            lines += [
                "### Top 5 Longs",
                "| Ticker | Score |",
                "|--------|-------|",
            ]
            for _, row in top_5.iterrows():
                lines.append(f"| {row['ticker']} | {row[score_col]:.4f} |")
            lines.append("")

    # Factor IC snapshot
    if factor_ic is not None and not factor_ic.empty:
        lines += [
            "## Factor IC (Latest)",
            "",
            "| Factor | IC |",
            "|--------|-----|",
        ]
        ic_col = "mean_ic" if "mean_ic" in factor_ic.columns else factor_ic.columns[-1]
        for _, row in factor_ic.head(config.top_n_factors).iterrows():
            lines.append(f"| {row.get('factor', '—')} | {row.get(ic_col, 0):.4f} |")
        lines.append("")

    # Positions
    if positions is not None and not positions.empty:
        total_value = (
            positions.get("value", 0).sum() if "value" in positions.columns else 0
        )
        lines += [
            "## Current Positions",
            "",
            f"**Total Value**: ${total_value:,.0f}  ",
            f"**Positions**: {len(positions)}  ",
            "",
        ]

    lines.append(f"*Auto-generated by report_generator.py — {today.strftime('%H:%M')}*")
    return "\n".join(lines)


# ── Weekly Report ──────────────────────────────────────────


def generate_weekly_report(
    equity_curve: pd.Series | None = None,
    returns: pd.Series | None = None,
    trades: pd.DataFrame | None = None,
    factor_performance: dict | None = None,
    risk_summary: dict | None = None,
    rebalance_events: pd.DataFrame | None = None,
    config: ReportConfig | None = None,
) -> str:
    """Generate weekly strategy performance report."""
    if config is None:
        config = ReportConfig()

    today = datetime.now()
    week_start = today - timedelta(days=today.weekday())
    lines = [
        f"# {config.strategy_name} — Weekly Report",
        f"**{week_start.strftime('%Y-%m-%d')} → {today.strftime('%Y-%m-%d')}**",
        "",
        "---",
        "",
    ]

    # Performance metrics
    if returns is not None and len(returns) > 0:
        weekly_ret = returns.tail(5)
        total_ret = float((1 + weekly_ret).prod() - 1)
        vol = float(weekly_ret.std() * np.sqrt(252))
        sharpe = float(weekly_ret.mean() / max(weekly_ret.std(), 1e-10) * np.sqrt(252))
        max_dd = float(
            ((1 + weekly_ret).cumprod() / (1 + weekly_ret).cumprod().cummax() - 1).min()
        )

        lines += [
            "## Performance Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Weekly Return | {total_ret:.2%} |",
            f"| Ann. Volatility | {vol:.2%} |",
            f"| Sharpe Ratio | {sharpe:.2f} |",
            f"| Max Drawdown | {max_dd:.2%} |",
        ]

        if equity_curve is not None and len(equity_curve) > 0:
            lines.append(f"| Current Equity | ${equity_curve.iloc[-1]:,.0f} |")
        lines.append("")

    # Risk summary
    if risk_summary and config.include_risk_metrics:
        lines += [
            "## Risk Metrics",
            "",
            "| Metric | Value |",
            "|--------|-------|",
        ]
        for k, v in risk_summary.items():
            if isinstance(v, (int, float)):
                lines.append(f"| {k} | {v:.4f} |")
        lines.append("")

    # Factor performance
    if factor_performance and config.include_factor_analysis:
        lines += ["## Factor Performance", ""]
        ic_data = factor_performance.get("ic_summary")
        if ic_data is not None and not (hasattr(ic_data, "empty") and ic_data.empty):
            if hasattr(ic_data, "to_markdown"):
                lines.append(ic_data.head(10).to_markdown(index=False))
            lines.append("")

    # Rebalancing
    if rebalance_events is not None and not rebalance_events.empty:
        lines += [
            "## Rebalancing Activity",
            "",
            f"**Events**: {len(rebalance_events)}  ",
            f"**Avg Turnover**: {rebalance_events.get('turnover_pct', pd.Series([0])).mean():.2f}%  ",
            "",
        ]

    # Trades
    if trades is not None and not trades.empty:
        n_buys = int((trades.get("action", "") == "buy").sum())
        n_sells = int((trades.get("action", "") == "sell").sum())
        lines += [
            "## Trade Summary",
            "",
            f"**Total Trades**: {len(trades)} | **Buys**: {n_buys} | **Sells**: {n_sells}  ",
            "",
        ]

    lines.append(f"*Auto-generated by report_generator.py — {today.strftime('%H:%M')}*")
    return "\n".join(lines)


# ── Monthly Report ─────────────────────────────────────────


def generate_monthly_report(
    returns: pd.Series | None = None,
    equity_curve: pd.Series | None = None,
    attribution: dict | None = None,
    stress_result: dict | None = None,
    factor_analysis: dict | None = None,
    covariance_comparison: pd.DataFrame | None = None,
    tca_summary: dict | None = None,
    config: ReportConfig | None = None,
) -> str:
    """Generate comprehensive monthly strategy review."""
    if config is None:
        config = ReportConfig()

    today = datetime.now()
    month_start = today.replace(day=1)
    lines = [
        f"# {config.strategy_name} — Monthly Report",
        f"**{month_start.strftime('%Y-%m-%d')} → {today.strftime('%Y-%m-%d')}**",
        "",
        "---",
        "",
    ]

    # Monthly performance
    if returns is not None and len(returns) > 0:
        monthly_ret = returns.tail(21)
        total_ret = float((1 + monthly_ret).prod() - 1)
        vol = float(monthly_ret.std() * np.sqrt(252))
        sharpe = float(
            monthly_ret.mean() / max(monthly_ret.std(), 1e-10) * np.sqrt(252)
        )
        calmar = total_ret / max(
            abs(
                float(
                    (
                        (1 + monthly_ret).cumprod()
                        / (1 + monthly_ret).cumprod().cummax()
                        - 1
                    ).min()
                )
            ),
            1e-10,
        )

        lines += [
            "## Monthly Performance",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Monthly Return | {total_ret:.2%} |",
            f"| Ann. Volatility | {vol:.2%} |",
            f"| Sharpe Ratio | {sharpe:.2f} |",
            f"| Calmar Ratio | {calmar:.2f} |",
        ]
        if equity_curve is not None:
            lines.append(f"| Current Equity | ${equity_curve.iloc[-1]:,.0f} |")
        lines.append("")

    # Performance attribution
    if attribution and config.include_performance_attribution:
        lines += [
            "## Performance Attribution",
            "",
            f"**R^2**: {attribution.get('r_squared', 0):.4f}  ",
            f"**Alpha (annual)**: {attribution.get('alpha_annual', 0):.4%}  ",
            "",
            "### Factor Contributions",
            "",
            "| Factor | Exposure | T-Stat | Annual Contrib |",
            "|--------|----------|--------|---------------|",
        ]
        exposures = attribution.get("exposures", {})
        tstats = attribution.get("t_statistics", {})
        contribs = attribution.get("factor_contributions", {})
        for name in exposures:
            if name in ("alpha", "const"):
                continue
            lines.append(
                f"| {name} | {exposures[name]:.4f} | {tstats.get(name, 0):.2f} | "
                f"{contribs.get(name, 0) * 252:.2%} |"
            )
        lines.append("")

    # Stress test
    if stress_result and config.include_stress_test:
        lines += [
            "## Stress Test",
            "",
            f"**Stress Score**: {stress_result.get('stress_score', 0):.2%}  ",
            f"**Worst Scenario**: {stress_result.get('worst_scenario', 'N/A')}  ",
            "",
            "| Scenario | Return | MaxDD | VaR 95% |",
            "|----------|--------|-------|---------|",
        ]
        for s in stress_result.get("scenarios", [])[:5]:
            lines.append(
                f"| {s['scenario']} | {s['total_return']:.1%} | "
                f"{s['max_drawdown']:.1%} | {s['var_95']:.1%} |"
            )
        lines.append("")

    # Factor analysis
    if factor_analysis and config.include_factor_analysis:
        lines += ["## Factor Analysis", ""]
        ic_sum = factor_analysis.get("ic_summary")
        if ic_sum is not None and not (hasattr(ic_sum, "empty") and ic_sum.empty):
            lines.append("### IC Summary (Top 5)")
            lines.append("")
            lines.append("| Factor | Mean IC | IC IR | Hit Rate | Decay (days) |")
            lines.append("|--------|---------|-------|----------|-------------|")
            for _, row in ic_sum.head(5).iterrows():
                lines.append(
                    f"| {row['factor']} | {row['mean_ic']:.4f} | "
                    f"{row['ic_ir']:.2f} | {row['hit_rate']:.2%} | {row['ic_decay_days']:.0f} |"
                )
            lines.append("")

    # Transaction cost
    if tca_summary and config.include_execution_summary:
        lines += [
            "## Execution Quality",
            "",
            f"**Avg Implementation Shortfall**: {tca_summary.get('avg_is_bp', 0):.1f} bp  ",
            f"**Avg VWAP Slippage**: {tca_summary.get('avg_vwap_slippage_bp', 0):.1f} bp  ",
            f"**Trades**: {tca_summary.get('n_trades', 0)}  ",
            "",
        ]

    # Covariance
    if covariance_comparison is not None and not covariance_comparison.empty:
        lines += [
            "## Covariance Estimation",
            "",
            covariance_comparison.to_markdown(index=False),
            "",
        ]

    lines.append(f"*Auto-generated by report_generator.py — {today.strftime('%H:%M')}*")
    return "\n".join(lines)


# ── Full report pipeline ───────────────────────────────────


def generate_full_report(
    report_type: str,
    **kwargs,
) -> tuple[str, str]:
    """Generate and save a report to disk.

    Parameters
    ----------
    report_type: "daily" | "weekly" | "monthly"
    kwargs: passed to the specific generator

    Returns (report_content, file_path).
    """
    generators = {
        "daily": generate_daily_briefing,
        "weekly": generate_weekly_report,
        "monthly": generate_monthly_report,
    }
    gen = generators.get(report_type, generate_daily_briefing)
    config = kwargs.pop("config", ReportConfig())
    output_dir = kwargs.pop("output_dir", config.output_dir)
    config.output_dir = output_dir
    report = gen(**kwargs, config=config)

    # Save to disk
    output_dir = Path(config.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M")
    fpath = output_dir / f"{report_type}_{ts}.md"
    fpath.write_text(report, encoding="utf-8")

    return report, str(fpath)


# ── Demo ────────────────────────────────────────────────────


def _make_demo_data() -> dict:
    """Create demo data covering all report inputs."""
    rng = np.random.default_rng(42)
    n = 252
    dates = pd.date_range("2024-01-01", periods=n, freq="B")
    tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "JPM"]

    returns = pd.Series(rng.normal(0.001, 0.018, n), index=dates)
    equity = (1 + returns).cumprod() * 1_000_000

    signals = pd.DataFrame(
        {
            "ticker": np.tile(tickers, 5),
            "signal": rng.choice([-1, 0, 1], len(tickers) * 5, p=[0.2, 0.4, 0.4]),
            "combined_score": rng.normal(0, 1, len(tickers) * 5),
        }
    )

    positions = pd.DataFrame(
        {
            "ticker": tickers[:5],
            "shares": rng.integers(100, 5000, 5),
            "weight": [0.30, 0.25, 0.20, 0.15, 0.10],
            "value": rng.integers(10000, 500000, 5),
        }
    )

    factor_ic = pd.DataFrame(
        {
            "factor": [f"factor_{i}" for i in range(8)],
            "mean_ic": rng.normal(0.02, 0.03, 8),
            "ic_ir": np.abs(rng.normal(0.5, 0.3, 8)),
            "hit_rate": rng.uniform(0.5, 0.7, 8),
            "ic_decay_days": rng.uniform(3, 30, 8),
        }
    ).sort_values("mean_ic", ascending=False)

    risk_summary = {
        "Sharpe": 1.35,
        "Sortino": 1.82,
        "Calmar": 0.95,
        "MaxDD": -0.15,
        "VaR_95": -0.022,
        "CVaR_95": -0.031,
    }

    attribution = {
        "r_squared": 0.88,
        "alpha_annual": 0.045,
        "exposures": {"MKT": 1.02, "SMB": 0.28, "HML": -0.15, "MOM": 0.12},
        "t_statistics": {"MKT": 45.3, "SMB": 8.7, "HML": -5.2, "MOM": 4.1},
        "factor_contributions": {
            "MKT": 0.0005,
            "SMB": 0.0002,
            "HML": -0.0001,
            "MOM": 0.0001,
        },
    }

    stress = {
        "stress_score": -0.18,
        "worst_scenario": "2008 GFC",
        "scenarios": [
            {
                "scenario": "2020 COVID Crash",
                "total_return": -0.25,
                "max_drawdown": -0.34,
                "var_95": -0.06,
            },
            {
                "scenario": "2008 GFC",
                "total_return": -0.32,
                "max_drawdown": -0.50,
                "var_95": -0.08,
            },
        ],
    }

    tca = {"avg_is_bp": 3.2, "avg_vwap_slippage_bp": -1.5, "n_trades": 42}

    return {
        "signals": signals,
        "positions": positions,
        "pnl": returns * 50000,
        "factor_ic": factor_ic,
        "returns": returns,
        "equity_curve": equity,
        "risk_summary": risk_summary,
        "attribution": attribution,
        "stress_result": stress,
        "tca_summary": tca,
        "factor_analysis": {"ic_summary": factor_ic},
    }


def main():
    data = _make_demo_data()
    config = ReportConfig(output_dir="company/reports")

    daily = generate_daily_briefing(
        signals=data["signals"],
        positions=data["positions"],
        pnl=data["pnl"],
        factor_ic=data["factor_ic"],
        config=config,
    )
    print(daily[:800])
    print("\n...\n")

    monthly = generate_monthly_report(
        returns=data["returns"],
        equity_curve=data["equity_curve"],
        attribution=data["attribution"],
        stress_result=data["stress_result"],
        tca_summary=data["tca_summary"],
        factor_analysis=data["factor_analysis"],
        config=config,
    )
    print(monthly[:800])

    # Save reports
    _, dp = generate_full_report(
        "daily", signals=data["signals"], positions=data["positions"], pnl=data["pnl"]
    )
    _, mp = generate_full_report(
        "monthly", returns=data["returns"], attribution=data["attribution"]
    )
    print(f"\nSaved: {dp}")
    print(f"Saved: {mp}")


def export_pdf(
    markdown_content: str, output_path: str, title: str = "Quant Report"
) -> str:
    """Export a markdown report to PDF using weasyprint (T877).

    Converts markdown → HTML → PDF with basic styling.
    Requires: pip install weasyprint
    """
    try:
        from weasyprint import HTML
    except ImportError:
        raise ImportError("weasyprint not installed. Run: pip install weasyprint")

    # Minimal markdown → HTML conversion (handles basic markdown tables/lists/headers)
    html_body = _markdown_to_html(markdown_content)
    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{title}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a1a; }}
  h1 {{ color: #0a0e17; border-bottom: 2px solid #f0b90b; padding-bottom: 8px; }}
  h2 {{ color: #1e293b; margin-top: 24px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th {{ background: #1e293b; color: #e2e8f0; padding: 8px 12px; text-align: left; }}
  td {{ padding: 6px 12px; border-bottom: 1px solid #e2e8f0; }}
  .positive {{ color: #10b981; }} .negative {{ color: #ef4444; }}
  code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 4px; }}
  pre {{ background: #1e293b; color: #e2e8f0; padding: 16px; border-radius: 8px; overflow-x: auto; }}
</style></head><body>{html_body}</body></html>"""

    HTML(string=html).write_pdf(output_path)
    return output_path


def _markdown_to_html(md: str) -> str:
    """Basic markdown → HTML for PDF export (no external deps)."""
    lines = md.split("\n")
    html_lines = []
    in_table = False
    in_code = False

    for line in lines:
        # Code blocks
        if line.startswith("```"):
            if in_code:
                html_lines.append("</pre>")
                in_code = False
            else:
                html_lines.append("<pre>")
                in_code = True
            continue
        if in_code:
            html_lines.append(line)
            continue

        # Headers
        if line.startswith("#### "):
            html_lines.append(f"<h4>{line[5:]}</h4>")
            continue
        if line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
            continue
        if line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
            continue
        if line.startswith("# "):
            html_lines.append(f"<h1>{line[2:]}</h1>")
            continue

        # Table rows
        if line.startswith("|") and line.endswith("|"):
            cells = [c.strip() for c in line[1:-1].split("|")]
            is_sep = all(
                c.replace("-", "").replace(":", "").strip() == "" for c in cells
            )
            if not in_table:
                html_lines.append("<table>")
                in_table = True
            if is_sep:
                continue  # skip separator row
            tag = (
                "th"
                if in_table and not any("<td>" in line for line in html_lines[-3:])
                else "td"
            )
            html_lines.append(
                "<tr>" + "".join(f"<{tag}>{c}</{tag}>" for c in cells) + "</tr>"
            )
            continue
        elif in_table:
            html_lines.append("</table>")
            in_table = False

        # Bold
        import re

        line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
        # Italic
        line = re.sub(r"\*(.+?)\*", r"<em>\1</em>", line)
        # Inline code
        line = re.sub(r"`(.+?)`", r"<code>\1</code>", line)

        if line.strip():
            html_lines.append(f"<p>{line}</p>")
        else:
            html_lines.append("<br>")

    if in_table:
        html_lines.append("</table>")
    if in_code:
        html_lines.append("</pre>")

    return "\n".join(html_lines)


if __name__ == "__main__":
    main()
